#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Build data/schedule.json (+ .js) for the Camp VC planner from the richer
Guidebook data produced by the sibling campvc-schedule project.

    python build_schedule.py [path-to-campvc-schedule] [--check]

It reads two files from that project (regenerated by `node build.js`):
  - rows.json    : the curated, de-duplicated schedule rows
  - bundle.json  : the full Guidebook bundle (descriptions, capacity,
                   registration dates, link categories)

and produces enriched activities, where:
  - activities are MERGED by name (case-insensitive) across venues; each
    instance carries its own venue + capacity,
  - booking vs drop-in is decided by registration_start_date (4 Jul = paid /
    phase 1; 11 Jul = included / phase 2; none = drop-in), with a small
    EXTERNAL_BOOKABLE override for trips booked off-app,
  - each activity carries description, capacity / total places, phase, and an
    externalBooking flag.

It also writes data/migrations.js mapping the previous build's activity ids to
the new (merged) ids, so friends' already-saved picks are remapped on load and
nothing is lost.
"""

import json
import os
import re
import sys
import unicodedata
from collections import OrderedDict

DAYS = ["Friday", "Saturday", "Sunday"]
DAY_INDEX = {d: i for i, d in enumerate(DAYS)}
OFFSITE_LOCATION = "(off-site / no venue listed)"
REG_PAID = "2026-07-04"      # paid sessions register first (phase 1)
REG_INCLUDED = "2026-07-11"  # included/free sessions register a week later (phase 2)

# Curated verdicts for no-registration activities (decided by reviewing their
# Guidebook descriptions): "bookable" = a real trip booked off-app, "turnup" =
# genuine drop-in. Keyed by normalised name. New/unknown no-reg activities are
# left unclassified and FLAGGED by the build (treated as drop-in until decided).
OVERRIDES_FILE = "dropin_overrides.json"
_overrides = None


def load_overrides():
    global _overrides
    if _overrides is None:
        try:
            with open(OVERRIDES_FILE, encoding="utf-8") as f:
                raw = json.load(f)
            _overrides = {k: (v.get("verdict") if isinstance(v, dict) else v) for k, v in raw.items()}
        except FileNotFoundError:
            _overrides = {}
    return _overrides


def to_minutes(value):
    if value is None:
        return None
    m = re.match(r"^(\d{1,2}):(\d{2})$", str(value).strip())
    return int(m.group(1)) * 60 + int(m.group(2)) if m else None


def fmt_time(minutes):
    return f"{minutes // 60:02d}:{minutes % 60:02d}"


def norm(text):
    """lowercase, strip accents/emoji, collapse spaces - for name matching."""
    t = unicodedata.normalize("NFKD", text or "").encode("ascii", "ignore").decode("ascii")
    return re.sub(r"\s+", " ", t).strip().lower()


def slugify(text):
    t = unicodedata.normalize("NFKD", text or "").encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-zA-Z0-9]+", "-", t).strip("-").lower() or "x"


def is_external_bookable(name):
    return load_overrides().get(norm(name)) == "bookable"


# Paid activities are booked through a third-party PARTNER LINK (off-app), not in
# the festival app - the description spells this out. Free/included activities
# book in-app. Detect the off-app ones from that booking-instructions wording.
_PARTNER_RE = re.compile(r"partner'?s?\s+link|third[\s-]?party|booking instructions|book and pay", re.I)


def books_off_app(description):
    return bool(_PARTNER_RE.search(description or ""))


# Some activities carry a registration date but the description says you don't
# need to book - those are really drop-ins. The description wins.
_NOBOOK_RE = re.compile(
    r"no booking (required|needed|necessary)|no need to book|just rock up"
    r"|no booking is (required|needed)|don't need to book|no pre[\s-]?booking", re.I)


def no_booking_required(description):
    return bool(_NOBOOK_RE.search(description or ""))


def is_open_window(start_raw, end_raw, start_min, end_min, name):
    """An open/all-day space you drop into anytime (vs a fixed-time session)."""
    s = str(start_raw or "").strip().lower()
    if s == "all day" or s == "":
        return True
    if start_min is None:
        return True
    if end_min is None or str(end_raw or "").strip() == "":
        return True
    if end_min > start_min and (end_min - start_min) >= 180:  # long open window (Calm Space, salons...)
        return True
    # (an event that crosses midnight, e.g. 23:00-00:30, is a real late session,
    #  not an open window - it's handled as a slot capped at midnight.)
    if re.search(r"drop.?in", name or "", re.I):
        return True
    return False


def load_inputs(sched_dir):
    with open(os.path.join(sched_dir, "rows.json"), encoding="utf-8") as f:
        rows = json.load(f)
    with open(os.path.join(sched_dir, "bundle.json"), encoding="utf-8") as f:
        bundle = json.load(f)
    return rows, bundle


def clean_html(html):
    text = re.sub(r"<[^>]+>", " ", html)
    text = (text.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
                .replace("&nbsp;", " ").replace("&#39;", "'").replace("&quot;", '"'))
    return re.sub(r"\s+", " ", text).strip()


def build_extras(bundle):
    """(normalised name, startTime) -> {desc, cap, reg, cats}."""
    extras = {}
    for e in bundle.get("guidebook_event", []):
        key = (norm(e.get("name", "")), str(e.get("startTime")))
        cats = []
        if e.get("links"):
            try:
                cats = [g.get("categoryTitle") for g in json.loads(e["links"])]
            except Exception:
                cats = []
        rec = {"desc": clean_html(e.get("description") or ""), "cap": e.get("max_capacity"),
               "reg": e.get("registration_start_date"), "cats": cats}
        if key not in extras or (rec["desc"] and not extras[key]["desc"]):
            extras[key] = rec
    return extras


def build(sched_dir):
    rows, bundle = load_inputs(sched_dir)
    extras = build_extras(bundle)

    activities = OrderedDict()  # norm(name) -> activity dict
    unclassified = set()        # no-reg activities with no curated verdict yet
    overrides = load_overrides()

    for r in rows:
        name = (r.get("Event") or "").strip()
        if not name:
            continue
        day = (r.get("Day") or "").strip()
        loc = (r.get("Location") or "").strip()
        start_min = to_minutes(r.get("Start"))
        end_min = to_minutes(r.get("End"))
        paid = str(r.get("PaidFree", "")).strip().lower() == "paid"
        cats = [c.strip() for c in str(r.get("Categories") or "").split(";") if c.strip()]
        ex = extras.get((norm(name), str(r.get("_start"))), {})
        reg = ex.get("reg")
        cap = ex.get("cap")
        desc = ex.get("desc", "")
        offsite = (loc == "")  # off-site trips have a blank venue in the source

        # Three properties, kept consistent:
        #   needs_booking - must be booked (reg, partner-link, or curated trip).
        #   external      - that booking happens off-app (third-party partner link).
        #   scheduled     - sits at a fixed time (so it's placed + clash-aware).
        # A no-booking timed event (Founders Talk) is scheduled but not booked;
        # an open all-day space (Calm Space) is neither - it's a window.
        partner = books_off_app(desc)
        ov = overrides.get(norm(name))
        if no_booking_required(desc):     # description explicitly says no booking - it's a drop-in/turn-up
            needs_booking, external = False, False
            scheduled = not is_open_window(r.get("Start"), r.get("End"), start_min, end_min, name)
        elif reg:
            needs_booking, external, scheduled = True, partner, True
        elif partner or ov == "bookable":
            needs_booking, external, scheduled = True, True, True
        else:
            needs_booking, external = False, False
            if ov is None:
                unclassified.add(name)
            scheduled = not is_open_window(r.get("Start"), r.get("End"), start_min, end_min, name)

        key = norm(name)
        if key not in activities:
            activities[key] = {"id": slugify(name), "name": name, "categories": [],
                               "paid": paid, "offsite": False, "external": False, "booking": False,
                               "description": "", "slots": [], "windows": []}
        a = activities[key]
        for c in cats:
            if c not in a["categories"]:
                a["categories"].append(c)
        if desc and not a["description"]:
            a["description"] = desc
        a["paid"] = a["paid"] or paid
        a["offsite"] = a["offsite"] or offsite
        a["external"] = a["external"] or external
        a["booking"] = a["booking"] or needs_booking

        # A real discrete SLOT has a daytime start (not a 00:00 placeholder) and,
        # on-site, a sensible length. Off-site trips may run long. Everything else
        # (long open windows like a massage tent, or junk midnight rows) is a
        # WINDOW - either earmarked (drop-in) or shown as a bookable appointment.
        crosses_midnight = end_min is not None and end_min <= start_min
        real_slot = (scheduled and start_min is not None and start_min > 0
                     and (offsite or end_min is None or crosses_midnight or (end_min - start_min) < 240))
        if real_slot:
            disp_end = end_min                       # for the label (real end, e.g. 00:30)
            sched_end = (24 * 60 if crosses_midnight  # runs into the night - cap at midnight for layout
                         else (end_min if end_min is not None else start_min + 50))
            a["slots"].append({
                "day": day, "day_index": DAY_INDEX.get(day, 9), "start_min": start_min,
                "end_min": sched_end,
                "label": f"{day} {fmt_time(start_min)}"
                         + (f"-{fmt_time(disp_end)}" if disp_end is not None else ""),
                "location": loc or "Off-site", "capacity": cap if isinstance(cap, int) else None})
        else:
            a["windows"].append({"day": day, "start": str(r.get("Start") or "").strip(),
                                 "end": str(r.get("End") or "").strip(), "location": loc or "Off-site"})

    out = []
    counts = {"repeating": 0, "oneoff": 0, "dropin": 0}
    for a in activities.values():
        slots = sorted(a["slots"], key=lambda s: (s["day_index"], s["start_min"]))
        kind = "repeating" if len(slots) >= 2 else ("oneoff" if len(slots) == 1 else "dropin")
        counts[kind] += 1
        caps = [s["capacity"] for s in slots if isinstance(s["capacity"], int) and s["capacity"] >= 0]
        unlimited = any((s["capacity"] is None or s["capacity"] < 0) for s in slots) if slots else True
        total_places = None if (unlimited or not caps) else sum(caps)
        out.append({
            "id": a["id"], "name": a["name"], "offsite": a["offsite"], "paid": a["paid"],
            "phase": 1 if a["paid"] else 2, "kind": kind,
            "booking": a["booking"], "external": a["external"],
            "description": a["description"], "categories": a["categories"],
            "maxPerSession": max(caps) if caps else None, "totalPlaces": total_places,
            "instances": [{"day": s["day"], "start_min": s["start_min"], "end_min": s["end_min"],
                           "label": s["label"], "location": s["location"], "capacity": s["capacity"]}
                          for s in slots],
            "windows": a["windows"]})
    return out, len(rows), counts, sorted(unclassified)


# ---------------- change detection (vs previous build) ----------------
SCHEDULE_JSON = "data/schedule.json"


def load_existing(path=SCHEDULE_JSON):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def label_set(act):
    return set(i["label"] for i in act.get("instances", []))


def diff_schedules(old_payload, new_acts):
    old = {a["id"]: a for a in (old_payload.get("activities", []) if old_payload else [])}
    new = {a["id"]: a for a in new_acts}
    added = [new[i] for i in new if i not in old]
    removed = [old[i] for i in old if i not in new]
    retimed = []
    for i, a in new.items():
        if i in old:
            at = sorted(label_set(a) - label_set(old[i]))
            rt = sorted(label_set(old[i]) - label_set(a))
            if at or rt:
                retimed.append((a, at, rt))
    return added, removed, retimed


def days_short(a):
    seen = []
    for i in (a.get("instances") or a.get("windows") or []):
        d = (i.get("day") or "")[:3]
        if d and d not in seen:
            seen.append(d)
    return ",".join(seen)


def format_changes(old_payload, added, removed, retimed):
    if old_payload is None:
        return "No previous schedule on disk - first build, nothing to compare.", False
    if not (added or removed or retimed):
        return "SCHEDULE CHANGES: none - identical to last build.", False
    L = ["SCHEDULE CHANGES (vs last build)", "=" * 34, "", f"NEW EVENTS ({len(added)}):"]
    for a in sorted(added, key=lambda x: x["name"]):
        n = len(a["instances"]) or len(a["windows"])
        L.append(f"  + {a['name']} - {n} session(s) ({days_short(a)}), {'Paid' if a['paid'] else 'Free'}")
    L += ["", f"REMOVED EVENTS ({len(removed)}):"]
    for a in sorted(removed, key=lambda x: x["name"]):
        L.append(f"  - {a['name']}")
    L += ["", f"TIMING CHANGES ({len(retimed)}):"]
    for a, at, rt in sorted(retimed, key=lambda x: x[0]["name"]):
        L.append(f"  ~ {a['name']}:")
        for t in rt:
            L.append(f"      removed: {t}")
        for t in at:
            L.append(f"      added:   {t}")
    return "\n".join(L), True


def build_migrations(old_payload, new_acts):
    """old activity id -> new (merged) id, so saved picks survive the rebuild."""
    new_ids = {a["id"] for a in new_acts}
    mig = {}
    for a in (old_payload.get("activities", []) if old_payload else []):
        new_id = slugify(a["name"])
        if a["id"] != new_id and new_id in new_ids:
            mig[a["id"]] = new_id
    return mig


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    check_only = "--check" in sys.argv[1:]
    sched_dir = args[0] if args else os.path.join("..", "campvc-schedule")

    activities, raw_count, counts, unclassified = build(sched_dir)
    old = load_existing()
    added, removed, retimed = diff_schedules(old, activities)
    report, changed = format_changes(old, added, removed, retimed)

    summary = (
        f"Source rows:         {raw_count}\n"
        f"Activities (merged): {len(activities)}\n"
        f"  repeating:         {counts['repeating']}\n"
        f"  one-off:           {counts['oneoff']}\n"
        f"  drop-in:           {counts['dropin']}\n"
        f"External-bookable:   {sum(1 for a in activities if a['external'])}\n")

    if check_only:
        print(summary)
        print(report)
        sys.exit(1 if changed else 0)

    os.makedirs("data", exist_ok=True)
    payload = {"days": DAYS, "activities": activities}
    if old is not None:
        with open("data/schedule.prev.json", "w", encoding="utf-8") as f:
            json.dump(old, f, ensure_ascii=False, indent=1)
    with open(SCHEDULE_JSON, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=1)
    with open("data/schedule.js", "w", encoding="utf-8") as f:
        f.write("window.SCHEDULE = ")
        json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    # migration map (merge old->new ids); accumulate across rebuilds so no id a
    # friend may still have saved is ever forgotten.
    mig = build_migrations(old, activities)
    existing_mig = {}
    if os.path.exists("data/migrations.json"):
        with open("data/migrations.json", encoding="utf-8") as f:
            existing_mig = json.load(f)
    existing_mig.update(mig)
    with open("data/migrations.json", "w", encoding="utf-8") as f:
        json.dump(existing_mig, f, ensure_ascii=False, indent=1)
    with open("data/migrations.js", "w", encoding="utf-8") as f:
        f.write("window.MIGRATIONS = ")
        json.dump(existing_mig, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    with open("data/CHANGES.md", "w", encoding="utf-8") as f:
        f.write("# Schedule change report\n\n```\n" + report + "\n```\n")

    print(summary)
    print(f"Migrations (old->new id): {len(existing_mig)} total")
    print()
    if unclassified:
        print("!! NEW no-registration activities NEEDING A BOOKABLE/TURN-UP DECISION")
        print("   (treated as drop-in for now - classify in dropin_overrides.json):")
        for n in unclassified:
            print(f"   - {n}")
    else:
        print("All no-registration activities are classified (dropin_overrides.json). Nothing to review.")
    print()
    print(report)
    print("\nWrote data/schedule.json, schedule.js, migrations.js, CHANGES.md")


if __name__ == "__main__":
    main()
